version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
      colors: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true

linters:
  default: standard
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - gosec
    - revive
    - staticcheck
    - unparam

  exclusions:
    generated: strict
    rules:
      - path: _test\.go
        linters:
          - gosec
          - unparam

  settings:
    revive:
      severity: warning
